# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(294, 425)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(5, 55, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(75, 55, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(145, 55, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(5, 125, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(75, 125, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(145, 125, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(5, 195, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(75, 195, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(145, 195, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(75, 265, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_0.setObjectName("pushButton_0")

        self.pushButton_ce = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ce.setGeometry(QtCore.QRect(5, 265, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ce.setFont(font)
        self.pushButton_ce.setStyleSheet("background-color: rgb(0, 255, 255);\n"
                                        "background-color: rgb(0, 170, 255);")
        self.pushButton_ce.setObjectName("pushButton_ce")

        self.pushButton_point = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_point.setGeometry(QtCore.QRect(145, 265, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_point.setFont(font)
        self.pushButton_point.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_point.setObjectName("pushButton_point")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(215, 55, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(215, 125, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_umn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_umn.setGeometry(QtCore.QRect(215, 195, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_umn.setFont(font)
        self.pushButton_umn.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_umn.setObjectName("pushButton_umn")
        self.pushButton_razd = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_razd.setGeometry(QtCore.QRect(215, 265, 70, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_razd.setFont(font)
        self.pushButton_razd.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_razd.setObjectName("pushButton_razd")
        self.pushButton_ravno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ravno.setGeometry(QtCore.QRect(5, 335, 280, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ravno.setFont(font)
        self.pushButton_ravno.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 170, 127);\n"
"background-color: rgb(255, 170, 127);\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_ravno.setObjectName("pushButton_ravno")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_funk(self):
        self.pushButton_0.clicked.connect(lambda: self.write_number(self.pushButton_0.text()))
        self.pushButton1.clicked.connect(lambda: self.write_number(self.pushButton1.text()))
        self.pushButton_2.clicked.connect(lambda: self.write_number(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write_number(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write_number(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda: self.write_number(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write_number(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write_number(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda: self.write_number(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda: self.write_number(self.pushButton_9.text()))
        self.pushButton_plus.clicked.connect(lambda: self.write_number(self.pushButton_plus.text()))
        self.pushButton_minus.clicked.connect(lambda: self.write_number(self.pushButton_minus.text()))
        self.pushButton_umn.clicked.connect(lambda: self.write_number(self.pushButton_umn.text()))
        self.pushButton_razd.clicked.connect(lambda: self.write_number(self.pushButton_razd.text()))


        self.pushButton_ce.clicked.connect(lambda: self.label.setText('0'))


        self.pushButton_ravno.clicked.connect(self.result)


    def write_number(self, number):
        if self.label.text() == '0':
            self.label.setText(number)
        else:
            self.label.setText((self.label.text() + number))


    def result(self):
        res = eval(self.label.text())
        print(res)
        self.label.setText(str(res))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_ce.setText(_translate("MainWindow", "C"))
        self.pushButton_point.setText(_translate("MainWindow", "."))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_umn.setText(_translate("MainWindow", "*"))
        self.pushButton_razd.setText(_translate("MainWindow", "/"))
        self.pushButton_ravno.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.add_funk()
    MainWindow.show()
    sys.exit(app.exec_())
